name: NuGet Package for UnturnedGuard.NuGetPackages

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/UnturnedGuard.NuGetPackages.yaml'
      - 'src/UnturnedGuard.NuGetPackages/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/UnturnedGuard.NuGetPackages.yaml'
      - 'src/UnturnedGuard.NuGetPackages/**'

jobs:
  build:
    name: "UnturnedGuard.NuGetPackages Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v3
      name: Setup .NET
      with:
        dotnet-version: 7.x
        
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: src/UnturnedGuard.NuGetPackages
        github_token: ${{ secrets.PAT }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true